DROP TABLE IF EXISTS DOCUMENTS;

CREATE TABLE DOCUMENTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  documentID VARCHAR(250) NOT NULL,
  documentName VARCHAR(250) NOT NULL,
  filePath VARCHAR(250) DEFAULT NULL,
  migration_status VARCHAR(250) DEFAULT NULL
);
